### ISSUE TITLE
User error: key "packages" not found

### ISSUE THREAD

**Issue by FPtje** [Avi-D-coder/implicit-hie#14]
When a `stack.yaml` file is missing the `packages` field, gen-hie will fail with the following error:

```
gen-hie: user error (AesonException "Error in $: key \"packages\" not found")
```

When adding the following to the stack.yaml file:

```
packages:
  - .
```

`gen-hie` works just fine. This seems redundant, though. Would it be possible to assume the singleton list containing `.` as default?

**Comment by fendor** [comment]
Does stack accept that? 0.o 
I always thought that is a mandatory field

**Comment by FPtje** [comment]
Yeah, stack appears to act the same with or without that field in this case.
