### ISSUE TITLE
Upload to hackage

### ISSUE THREAD

**Issue by jneira** [Avi-D-coder/implicit-hie#2]
Now that we are suggesting in hls the tool to help generate the hie.yaml, it would be great that users could install it with stack or cabal, without having to checkout the project.

**Comment by Avi-D-coder** [comment]
Yep will do tomorrow. Already made an account

**Comment by Avi-D-coder** [comment]
This is going to wait another day, I realized I'm not handling exe other-modules. It's an easy fix but I didn't get to it today.

**Comment by Avi-D-coder** [comment]
This is done, but I still need to provide hie-bios cradles. 
That will be a different package, since I don't want this one to depend on hie-bios.
