### ISSUE TITLE
Multi Cradle: No prefixes matched2

### ISSUE THREAD

**Issue by adamschoenemann** [Avi-D-coder/implicit-hie#21]
Thanks for writing this utility!
I used it and it works wonders, but I get the above error for the "Paths_" module that cabal generates.

**Comment by jneira** [comment]
Hi, where do you get the error? with the utility itself or using the generated `hie.yaml` with haskell-language-server o rghcide?

**Comment by adamschoenemann** [comment]
Right, while using the generated `hie.yaml` with haskell-language-server and VSCode

**Comment by jneira** [comment]
I am afraid that handling of `Paths_package_name` is one of the known limitations of the tool. 
However you can change the generated `hie.yaml` to make hls load them adding:
```
- path: dist-newstyle
  component: myproject:lib
```
as described here: https://github.com/haskell/ghcide/issues/574#issuecomment-638716328

**Comment by adamschoenemann** [comment]
Great, thanks for the help :)
