### ISSUE TITLE
If I have both then can I pick stack?

### ISSUE THREAD

**Issue by philderbeast** [Avi-D-coder/implicit-hie#3]
I have a project I build with both cabal v2 and stack. Could we please supplement the logic here so that if I have both then there's a way for me to choose stack?

https://github.com/Avi-D-coder/implicit-hie/blob/88e8f1cf96c6d998db6e2b25ec3d3a3c14b6e6b6/app/Main.hs#L23-L28

**Comment by Avi-D-coder** [comment]
I would happily take a PR that added this as a flag.

**Comment by fendor** [comment]
I think it would also make sense to be able to specify it on the cli.
E.g. `gen-hie --stack`

**Comment by Avi-D-coder** [comment]
Yeah I was meaning something like `gen-hie --type stack`, but `--stack` or `--cabal` works too
