### ISSUE TITLE
Empty `other-modules` leads to wrong output

### ISSUE THREAD

**Issue by michaelpj** [Avi-D-coder/implicit-hie#30]
We have a stanza like this:
```
executable prism-unlock-exchange
    hs-source-dirs: prism/unlock-exchange
    other-modules:
    build-depends:
        base >=4.9 && <5
```
which gives output like this:
```
    - path: "plutus-scb/prism/unlock-exchange"
      component: "plutus-scb:exe:prism-unlock-exchange"
    - path: "plutus-scb/prism/unlock-exchange/build-depends:.hs"
      component: "plutus-scb:exe:prism-unlock-exchange"
    - path: "plutus-scb/prism/unlock-exchange/base.hs"
      component: "plutus-scb:exe:prism-unlock-exchange"
```

i.e. it's taking the cabal syntax after `other-modules` as, well, modules.

Not sure if this is related to https://github.com/Avi-D-coder/implicit-hie/issues/17.

**Comment by michaelpj** [comment]
Maybe also: https://github.com/Avi-D-coder/implicit-hie/issues/29#issuecomment-731967670

**Comment by jneira** [comment]
I wonder if it is time to revive #13 and use directly cabal parsers.

**Comment by Avi-D-coder** [comment]
I'll take a look at this tomorrow.

**Comment by Avi-D-coder** [comment]
@michaelpj When you get a chance could you make sure your issue is fixed, before I bump ghcide and hls dependence constraint.
