### ISSUE TITLE
Where does `gen-hie` come from

### ISSUE THREAD

**Issue by peni4142** [Avi-D-coder/implicit-hie#33]
Hello
Maybe I am a dummy,

but I have no idea how to use gen-hie.
I am working in a virtual box. The os in the virtual box is ubuntu.

An explanation how to make `gen-hie` available would be nice.

```
gen-hie > hie.yaml
gen-hie: command not found
```
Best Regards

**Comment by jneira** [comment]
don't worry, you need to install the executable first with `cabal install implicit-hie` or `stack install implicit-hie`
