### ISSUE TITLE
Incorrect parsing of freeform fields

### ISSUE THREAD

**Issue by Ptival** [Avi-D-coder/implicit-hie#37]
I posted the longer details here:

https://github.com/haskell/haskell-language-server/issues/2012

but the gist is that freeform field lines that start with a "section" keyword are incorrectly parsed as sections.

I think I can come up with a half decent candidate patch, then you might want to tweak it and add some regression testing.

**Comment by Avi-D-coder** [comment]
Thank you, I released your change in [0.1.2.6](https://hackage.haskell.org/package/implicit-hie-0.1.2.6)!
