### ISSUE TITLE
implicit-hie doesn't recognize foreign-library sections in cabal

### ISSUE THREAD

**Issue by cdsmith** [Avi-D-coder/implicit-hie#44]
I was attempting to follow the tutorial at https://nokomprendo.gitlab.io/posts/tuto_075/2021-09-12-fr-README.html

HLS is flagging the Binding module with `Multi Cradle: no prefixes matched`.  The module is listed in the `other-modules` section of a `foreign-library` section in the cabal file, as follows:

```
foreign-library fibohs
    type:               native-shared
    cc-options:         -std=c++17
    c-sources:          cbits/binding.cpp
    install-includes:   cbits/binding.hpp
    hs-source-dirs:     ffi
    build-depends:      ffi, base
    other-modules:      Binding
```

Adding this `hie.yaml`

```
cradle:
  cabal:
```

fixes the problem, which indicates this is a problem with implicit-hie.

**Comment by Avi-D-coder** [comment]
The fix is published in `0.1.2.7`.
This should be fixed once HLS picks up the new version.
